networks:
  tasknet:
    driver: bridge

services:
  backend:
    build: ./backend
    container_name: taskmanager_backend
    ports:
      - "5001:5001"
    networks:
      - tasknet

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - tasknet

  cypress:
    image: cypress/included:15.3.0
    depends_on:
      - backend
      - frontend
    environment:
      - CYPRESS_BASE_URL=http://frontend:80
      - CYPRESS_BACKEND_URL=http://backend:5001
    working_dir: /e2e
    volumes:
      - ./cypress:/e2e
    networks:
      - tasknet
    command: npx cypress run