name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd frontend && npm install
          npm install --save-dev concurrently cypress wait-on

      - name: Start backend and frontend
        run: npm run start:dev &
      
      - name: Wait for servers
        run: |
          npx wait-on http://localhost:3000
          npx wait-on http://localhost:5000

      - name: Run Cypress tests
        run: npm run cypress:run